Repository Team-Clody/Clody_Android, pull requests merged in 2024-09, with the labels that each got.

#196 [FIX/#175] 2차 스프린트 QA 반영
  app/src/main/java/com/sopt/clody/presentation/ui/auth/screen/NicknameScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DailyDiaryCard.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DailyDiaryCardContent.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/component/HomeTopAppBar.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/component/YearAndMonthTitle.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/AccountManagementLogoutOption.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/AccountManagementNicknameOption.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/LogoutDialog.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/NicknameChangeBottomSheet.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/NicknameChangeTextField.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/SettingOption.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/notificationsetting/component/DiaryAlarmSwitch.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/notificationsetting/component/NotificationSettingTime.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/notificationsetting/component/NotificationSettingTimePicker.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/notificationsetting/component/ReplyAlarmSwitch.kt
  app/src/main/res/drawable/ic_notification_setting_switch_thumb.xml
  app/src/main/res/drawable/ic_toast_check_on_18.xml
  app/src/main/res/values/strings.xml
Labels: 🔥 민재, 🛠️ FIX

#199 [REFACTOR/#197] 재발급 로직 수정
  app/src/main/java/com/sopt/clody/data/remote/interceptor/AuthInterceptor.kt
Labels: 🌊 문수, 🛠️ FIX

#200 [Add/#195] firebase crashlytics
  app/build.gradle.kts
  app/proguard-rules.pro
  build.gradle.kts
  gradle/libs.versions.toml
Labels: ➕ ADD, 🌊 문수

#205 [Refactor/#202] Test 서버 분리 및 반영
  app/build.gradle.kts
  app/src/main/java/com/sopt/clody/data/remote/dto/response/ResponseDiaryTimeDto.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/screen/ReplyLoadingViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/screen/WriteDiaryViewModel.kt
Labels: ♻️ REFACTOR, 🌊 문수

#208 [Refactor/#207] 최초 답장 로딩 시간 변경 및 답장 null 대응
  app/build.gradle.kts
  app/src/main/java/com/sopt/clody/data/remote/dto/ResponseReplyDiaryDto.kt
  app/src/main/java/com/sopt/clody/data/repositoryimpl/ReplyDiaryRepositoryImpl.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replydiary/ReplyDiaryViewModel.kt
Labels: ♻️ REFACTOR, 🌊 문수

#210 [REFACTOR/#209] 홈 에러대응 수정
  app/build.gradle.kts
  app/src/main/java/com/sopt/clody/data/repositoryimpl/DailyDiariesRepositoryImpl.kt
  app/src/main/java/com/sopt/clody/data/repositoryimpl/MonthlyCalendarRepositoryImpl.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/utils/network/NetworkErrorMessage.kt
Labels: ♻️ REFACTOR, 🌊 문수
