Repository Team-Clody/Clody_Android, pull requests merged in 2024-07, with the labels that each got.

#4 [SETTING/#1] 프로젝트 기초 세팅
  .editorconfig
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/clody/ClodyApp.kt
  app/src/main/java/com/sopt/clody/data/datastore/SecureDataStore.kt
  app/src/main/java/com/sopt/clody/data/datastore/SecureDataStoreImpl.kt
  app/src/main/java/com/sopt/clody/data/local/datasource/LocalDataSource.kt
  app/src/main/java/com/sopt/clody/data/local/datasourceimpl/LocalDataSourceImpl.kt
  app/src/main/java/com/sopt/clody/data/remote/api/AnotherApiService.kt
  app/src/main/java/com/sopt/clody/data/remote/api/ApiService.kt
  app/src/main/java/com/sopt/clody/data/remote/datasource/RemoteDataSource.kt
  app/src/main/java/com/sopt/clody/data/remote/datasourceimpl/RemoteDataSourceImpl.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/ExampleRequestDto.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/ExampleResponseDto.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/base/ApiResponse.kt
  app/src/main/java/com/sopt/clody/data/remote/interceptor/AuthInterceptor.kt
  app/src/main/java/com/sopt/clody/data/remote/mapper/ExampleMapper.kt
  app/src/main/java/com/sopt/clody/data/repository/ExampleRepository.kt
  app/src/main/java/com/sopt/clody/data/repositoryimpl/ExampleRepositoryImpl.kt
  app/src/main/java/com/sopt/clody/di/ApiModule.kt
  app/src/main/java/com/sopt/clody/di/DataSourceModule.kt
  app/src/main/java/com/sopt/clody/di/DataStoreModule.kt
  app/src/main/java/com/sopt/clody/di/NetworkModule.kt
  app/src/main/java/com/sopt/clody/di/Qualifier.kt
  app/src/main/java/com/sopt/clody/di/RepositoryModule.kt
  app/src/main/java/com/sopt/clody/domain/model/ExampleModel.kt
  app/src/main/java/com/sopt/clody/domain/usecase/GetAllExamplesUseCase.kt
  app/src/main/java/com/sopt/clody/presentation/ExampleScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ExampleViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/MainActivity.kt
  app/src/main/java/com/sopt/clody/utils/base/UiState.kt
  app/src/main/java/com/sopt/clody/utils/base/ValidationResult.kt
  app/src/main/java/com/sopt/clody/utils/extension/ComposeViewExt.kt
  app/src/main/java/com/sopt/clody/utils/extension/StringExt.kt
  app/src/main/java/com/sopt/clody/utils/extension/handleApiResponse.kt
  build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: ⚙ SETTING, 🌊 문수

#5 [SETTING/#3] color font asset setting
  app/src/main/java/com/sopt/clody/ui/theme/Color.kt
  app/src/main/java/com/sopt/clody/ui/theme/Theme.kt
  app/src/main/java/com/sopt/clody/ui/theme/Type.kt
  app/src/main/res/font/pretendard_medium.ttf
  app/src/main/res/font/pretendard_semibold.ttf
Labels: ⚙ SETTING, 🔥 민재

#7 [FIX/#6] color, font asset setting naming fix
  app/src/main/java/com/sopt/clody/ui/theme/Color.kt
  app/src/main/java/com/sopt/clody/ui/theme/Theme.kt
  app/src/main/java/com/sopt/clody/ui/theme/Type.kt
Labels: ❤️‍🩹 CHORE, 🔥 민재

#13 [FEAT/#12] Jetpack Navigation 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/clody/presentation/ExampleScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ExampleViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/MainActivity.kt
  app/src/main/java/com/sopt/clody/presentation/NavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/auth/RegisterScreen.kt
  app/src/main/java/com/sopt/clody/presentation/auth/TermsOfServiceScreen.kt
  app/src/main/java/com/sopt/clody/presentation/main/MainActivity.kt
  app/src/main/java/com/sopt/clody/presentation/main/MainNavHost.kt
  app/src/main/java/com/sopt/clody/presentation/main/MainNavigator.kt
Labels: ✨ FEAT, 🌊 문수

#14 [UI/#8] '일기모아보기' 리스트뷰 UI 구현
  app/src/main/java/com/sopt/clody/presentation/diarylist/component/DailyDiaryCard.kt
  app/src/main/java/com/sopt/clody/presentation/diarylist/component/DailyDiaryCardItem.kt
  app/src/main/java/com/sopt/clody/presentation/diarylist/component/DiaryListTopAppBar.kt
  app/src/main/java/com/sopt/clody/presentation/diarylist/component/MonthlyDiaryList.kt
  app/src/main/java/com/sopt/clody/presentation/diarylist/screen/ListViewScreen.kt
  app/src/main/res/drawable/ic_listview_calendar.xml
  app/src/main/res/drawable/ic_listview_clover.xml
  app/src/main/res/drawable/ic_listview_delete.xml
  app/src/main/res/drawable/ic_listview_kebab_menu.xml
Labels: 🎨 UI, 🔥 민재

#16 [FIX/#15] style guide update
  app/src/main/java/com/sopt/clody/ui/theme/Color.kt
  app/src/main/java/com/sopt/clody/ui/theme/Type.kt
  app/src/main/res/font/pretendard_regular.ttf
Labels: 🔥 민재, 🛠️ FIX

#21 [UI/#11] 공통 컴포넌트 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/clody/data/repositoryimpl/ExampleRepositoryImpl.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/component/BottomSheetTimePicker.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/screen/RegisterScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/screen/TermsOfServiceScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/bottomsheet/ClodyBottomSheet.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/button/ClodyButton.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/popup/ClodyPopupBottomSheet.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/timepicker/ClodyPicker.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/timepicker/PickerState.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DailyDiaryCard.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DailyDiaryCardItem.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DiaryListTopAppBar.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/MonthlyDiaryList.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/screen/ListViewScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/sopt/clody/presentation/ui/navigatior/MainNavHost.kt
  app/src/main/java/com/sopt/clody/presentation/ui/navigatior/MainNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/navigatior/NavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/utils/base/UiState.kt
  app/src/main/java/com/sopt/clody/presentation/utils/base/ValidationResult.kt
  app/src/main/java/com/sopt/clody/presentation/utils/extension/ComposeViewExt.kt
  app/src/main/java/com/sopt/clody/presentation/utils/extension/StringExt.kt
  app/src/main/java/com/sopt/clody/presentation/utils/extension/handleApiResponse.kt
Labels: 🎨 UI, 🌊 문수

#23 [UI/#22] 설정 UI 구현
  app/src/main/java/com/sopt/clody/presentation/ui/component/bottomsheet/ClodyBottomSheet.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/button/ClodyButton.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/dialog/ClodyDialog.kt
  app/src/main/java/com/sopt/clody/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/sopt/clody/presentation/ui/navigatior/MainNavHost.kt
  app/src/main/java/com/sopt/clody/presentation/ui/navigatior/MainNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/LogoutDialog.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/NicknameChangeModalBottomSheet.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/NicknameChangeTextField.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/SettingOption.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/SettingSeparateLine.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/SettingTopAppBar.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/navigation/SettingNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/navigation/SettingNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/AccountManagementScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/NotificationSettingScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/SettingScreen.kt
  app/src/main/java/com/sopt/clody/ui/theme/Type.kt
  app/src/main/res/drawable/ic_account_management_clover.xml
  app/src/main/res/drawable/ic_nickname_change_clean.xml
  app/src/main/res/drawable/ic_nickname_change_dismiss.xml
  app/src/main/res/drawable/ic_setting_back.xml
  app/src/main/res/drawable/ic_setting_next.xml
  app/src/main/res/drawable/img_account_management_kakao.png
  app/src/main/res/values/strings.xml
Labels: 🎨 UI, 🔥 민재

#24 [UI/#10] 온보딩 UI 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/clody/presentation/ui/auth/component/button/KaKaoButton.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/component/button/NextButton.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/component/checkbox/CustomCheckBox.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/component/container/PickerBox.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/component/textfield/NickNameTextField.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/component/timepicker/BottomSheetTimePicker.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/navigation/AuthNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/navigation/AuthNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/screen/GuideScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/screen/NicknameScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/screen/RegisterScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/screen/SignUpScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/screen/TermsOfServiceScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/screen/TimeReminderScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/popup/ClodyPopupBottomSheet.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/timepicker/ClodyPicker.kt
  app/src/main/java/com/sopt/clody/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/sopt/clody/presentation/ui/navigatior/MainNavHost.kt
  app/src/main/java/com/sopt/clody/presentation/ui/navigatior/MainNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/navigatior/NavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/NotificationSettingScreen.kt
  app/src/main/res/drawable-xhdpi/img_guide_first.png
  app/src/main/res/drawable-xhdpi/img_guide_fourth.png
  app/src/main/res/drawable-xhdpi/img_guide_second.png
  app/src/main/res/drawable-xhdpi/img_guide_third.png
  app/src/main/res/drawable-xxhdpi/img_guide_first.png
  app/src/main/res/drawable-xxhdpi/img_guide_fourth.png
  app/src/main/res/drawable-xxhdpi/img_guide_second.png
  app/src/main/res/drawable-xxhdpi/img_guide_third.png
  app/src/main/res/drawable/ic__signup_title.xml
  app/src/main/res/drawable/ic_nickname_back.xml
  app/src/main/res/drawable/ic_nickname_delete.xml
  app/src/main/res/drawable/ic_picker_dismiss.xml
  app/src/main/res/drawable/ic_signup_kakao.xml
  app/src/main/res/drawable/ic_signup_logo.xml
  app/src/main/res/drawable/ic_signup_logotitle.xml
  app/src/main/res/drawable/ic_terms_check_off_23.xml
  app/src/main/res/drawable/ic_terms_check_off_25.xml
  app/src/main/res/drawable/ic_terms_check_on_23.xml
  app/src/main/res/drawable/ic_terms_check_on_25.xml
  app/src/main/res/drawable/ic_terms_next.xml
  app/src/main/res/drawable/ic_timereminder_down.xml
  app/src/main/res/drawable/img_guide_first.png
  app/src/main/res/drawable/img_guide_fourth.png
  app/src/main/res/drawable/img_guide_second.png
  app/src/main/res/drawable/img_guide_third.png
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 🎨 UI, 🌊 문수

#32 [UI/#28] 일기답장 로딩화면 구현
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/screen/ReplyLoadingScreen.kt
  app/src/main/res/drawable-xhdpi/img_loading_complete.png
  app/src/main/res/drawable-xhdpi/img_loading_wait.png
  app/src/main/res/drawable-xxhdpi/img_loading_complete.png
  app/src/main/res/drawable-xxhdpi/img_loading_wait.png
  app/src/main/res/drawable/img_loading_complete.png
  app/src/main/res/drawable/img_loading_wait.png
  app/src/main/res/values/strings.xml
Labels: 🎨 UI, 🌊 문수

#34 [UI/#26] 일기 모아보기 페이지 컴포넌트 추가
  app/build.gradle.kts
  app/src/main/java/com/sopt/clody/presentation/ui/auth/navigation/AuthNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/screen/GuideScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/bottomsheet/ClodyBottomSheet.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/dialog/ClodyDialog.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DailyDiaryCard.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DailyDiaryCardItem.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DiaryListTopAppBar.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/MonthlyDiaryList.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/YearMonthPicker.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/navigator/DiaryListNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/navigator/DiaryListNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/screen/DiaryListScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/screen/ListViewScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/sopt/clody/presentation/ui/navigatior/MainNavHost.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/SettingTopAppBar.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/navigation/SettingNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/AccountManagementScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/NotificationSettingScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/SettingScreen.kt
  app/src/main/res/drawable/ic_diary_delete_trash.xml
  app/src/main/res/drawable/ic_reply_diary_new.xml
  gradle/libs.versions.toml
Labels: 🎨 UI, 🔥 민재

#35 [UI/#33] 일기답변 UI 구현
  app/src/main/java/com/sopt/clody/presentation/MainActivity.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replydiary/CloverDialog.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replydiary/ReplyDiaryScreen.kt
  app/src/main/res/drawable-xhdpi/img_reply_logo.png
  app/src/main/res/drawable-xxhdpi/img_reply_logo.png
  app/src/main/res/drawable/ic_dialog_clover.xml
  app/src/main/res/drawable/img_reply_logo.png
  app/src/main/res/values/strings.xml
Labels: 🎨 UI, 🌊 문수

#36 [UI/#30] 알림시간 설정 변경뷰 구현
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/SettingBottomSheetTimePicker.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/NotificationSettingScreen.kt
Labels: 🎨 UI, 🌩️ 연진

#39 [UI/#38] splash 화면 구현
  app/build.gradle.kts
  app/src/main/java/com/sopt/clody/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/sopt/clody/presentation/ui/navigatior/MainNavHost.kt
  app/src/main/java/com/sopt/clody/presentation/ui/splash/SplashScreen.kt
  app/src/main/res/drawable-xhdpi/img_splash_logo.png
  app/src/main/res/drawable-xxhdpi/img_splash_logo.png
  app/src/main/res/drawable/img_splash_logo.png
  gradle/libs.versions.toml
Labels: 🎨 UI, 🌩️ 연진

#42 [UI/#31] 캘린더뷰 컴포넌트 추가 및 전체 뷰 네비게이션 연결
  app/src/main/java/com/sopt/clody/presentation/ui/auth/navigation/AuthNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/screen/GuideScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/screen/TermsOfServiceScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/YearMonthPicker.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/bottomsheet/DiaryDeleteSheet.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DailyDiaryCard.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/navigation/DiaryListNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/navigation/DiaryListNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/screen/DiaryListScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/calendar/ClodyCalendar.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/calendar/component/DailyDiaryListItem.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/component/CloverCount.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/component/DiaryStateButton.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/component/HomeTopAppBar.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/component/YearAndMonthTitle.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/navigation/HomeNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/navigation/HomeNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/sopt/clody/presentation/ui/navigatior/MainNavHost.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/NicknameChangeModalBottomSheet.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/AccountManagementScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/SettingScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/navigation/WriteDiaryNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/navigation/WriteDiaryNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/navigator/WriteDiaryNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/screen/WriteDiaryScreen.kt
Labels: 🎨 UI, 🔥 민재

#44 [FEAT/#40] 캘린더 api 연결
  app/src/main/java/com/sopt/clody/data/remote/api/ApiService.kt
  app/src/main/java/com/sopt/clody/data/remote/api/CalendarApiService.kt
  app/src/main/java/com/sopt/clody/data/remote/datasource/DailyDiariesDataSource.kt
  app/src/main/java/com/sopt/clody/data/remote/datasource/MonthlyCalendarDataSource.kt
  app/src/main/java/com/sopt/clody/data/remote/datasourceimpl/DailyDiariesDataSourcelmpl.kt
  app/src/main/java/com/sopt/clody/data/remote/datasourceimpl/MonthlyCalendarDataSourcelmpl.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/base/ApiResponse.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/response/DailyDiariesResponseDto.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/response/MonthlyCalendarResponseDto.kt
  app/src/main/java/com/sopt/clody/data/repository/DailyDiariesRepository.kt
  app/src/main/java/com/sopt/clody/data/repository/MonthlyCalendarRepository.kt
  app/src/main/java/com/sopt/clody/data/repositoryimpl/DailyDiariesRepositoryImpl.kt
  app/src/main/java/com/sopt/clody/data/repositoryimpl/MonthlyCalendarRepositoryImpl.kt
  app/src/main/java/com/sopt/clody/di/ApiModule.kt
  app/src/main/java/com/sopt/clody/di/DataSourceModule.kt
  app/src/main/java/com/sopt/clody/di/RepositoryModule.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/YearMonthPicker.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DiaryListTopAppBar.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/MonthlyDiaryList.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/screen/DiaryListScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/calendar/ClodyCalendar.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/calendar/component/DailyDiaryListItem.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/calendar/component/DayItem.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/calendar/component/MonthlyItem.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/calendar/component/WeekHeader.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/component/CloverCount.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/component/HomeTopAppBar.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/component/YearAndMonthTitle.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/navigatior/MainNavHost.kt
  app/src/main/java/com/sopt/clody/presentation/utils/extension/handleApiResponse.kt
Labels: ✨ FEAT, 🌩️ 연진

#48 [FEAT/#43] 일기 모아보기 페이지 API 연결
  app/src/main/java/com/sopt/clody/data/remote/api/DiaryListService.kt
  app/src/main/java/com/sopt/clody/data/remote/datasource/DiaryListDataSource.kt
  app/src/main/java/com/sopt/clody/data/remote/datasourceimpl/DiaryListDataSourceImpl.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/diarylist/ResponseMonthlyDiaryDto.kt
  app/src/main/java/com/sopt/clody/data/remote/interceptor/AuthInterceptor.kt
  app/src/main/java/com/sopt/clody/data/repository/DiaryListRepository.kt
  app/src/main/java/com/sopt/clody/data/repositoryimpl/DiaryListRepositoryImpl.kt
  app/src/main/java/com/sopt/clody/di/ApiModule.kt
  app/src/main/java/com/sopt/clody/di/DataSourceModule.kt
  app/src/main/java/com/sopt/clody/di/RepositoryModule.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/YearMonthPicker.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DailyDiaryCard.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DailyDiaryCardItem.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DiaryListTopAppBar.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/MonthlyDiaryList.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/screen/DiaryListScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/screen/DiaryListState.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/screen/DiaryListViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/component/HomeTopAppBar.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/component/YearAndMonthTitle.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/res/drawable/ic_listview_arrow_down.xml
  app/src/main/res/drawable/ic_listview_calendar.xml
Labels: ✨ FEAT, 🔥 민재

#53 [HOTFIX/#52] Conflict 해결
  app/src/main/java/com/sopt/clody/di/RepositoryModule.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/MonthlyDiaryList.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/navigation/DiaryListNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/screen/DiaryListScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/NotificationSettingScreen.kt
Labels: 🚨 HOTFIX, 🔥 민재

#55 [HOTFIX/#54] 로그인 에러응답 변경
  app/src/main/java/com/sopt/clody/di/DataSourceModule.kt
  app/src/main/java/com/sopt/clody/di/RepositoryModule.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/navigation/AuthNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/signup/SignUpScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/signup/SignUpViewModel.kt
Labels: 🚨 HOTFIX, 🌊 문수

#56 [FEAT/#49] 회원정보 접근 API 연결
  app/src/main/java/com/sopt/clody/data/remote/api/AccountManagementService.kt
  app/src/main/java/com/sopt/clody/data/remote/datasource/AccountManagementDataSource.kt
  app/src/main/java/com/sopt/clody/data/remote/datasourceimpl/AccountManagementDataSourceImpl.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/ResponseUserInfoDto.kt
  app/src/main/java/com/sopt/clody/data/repository/AccountManagementRepository.kt
  app/src/main/java/com/sopt/clody/data/repositoryimpl/AccountManagementRepositoryImpl.kt
  app/src/main/java/com/sopt/clody/di/ApiModule.kt
  app/src/main/java/com/sopt/clody/di/DataSourceModule.kt
  app/src/main/java/com/sopt/clody/di/RepositoryModule.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/screen/NicknameScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/NicknameChangeModalBottomSheet.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/AccountManagementScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/AccountManagementViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/NotificationSettingScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/UserInfoState.kt
  app/src/main/res/drawable-xhdpi/img_account_management_kakao.png
  app/src/main/res/drawable-xxhdpi/img_account_management_kakao.png
  app/src/main/res/img_account_management_kakao/kakao 2.png
  app/src/main/res/img_account_management_kakao/kakao 2@2x.png
  app/src/main/res/img_account_mangement_kakao/kakao 2@3x.png
Labels: ✨ FEAT, 🔥 민재

#59 [FEAT/#51] 일기작성 API 및 로딩 애니메이션 적용
  app/build.gradle.kts
  app/src/main/java/com/sopt/clody/data/remote/api/WriteDiaryService.kt
  app/src/main/java/com/sopt/clody/data/remote/datasource/WriteDiaryDataSource.kt
  app/src/main/java/com/sopt/clody/data/remote/datasourceimpl/WriteDiaryDataSourceImpl.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/RequestWriteDiaryDto.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/ResponseWriteDiaryDto.kt
  app/src/main/java/com/sopt/clody/data/repository/WriteDiaryRepository.kt
  app/src/main/java/com/sopt/clody/data/repositoryimpl/WriteDiaryRepositoryImpl.kt
  app/src/main/java/com/sopt/clody/di/ApiModule.kt
  app/src/main/java/com/sopt/clody/di/DataSourceModule.kt
  app/src/main/java/com/sopt/clody/di/RepositoryModule.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/calendar/ClodyCalendar.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/navigation/HomeNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/sopt/clody/presentation/ui/navigatior/MainNavHost.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/navigation/ReplyLoadingNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/navigation/ReplyLoadingNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/screen/ReplyLoadingScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/component/DiaryTitleText.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/navigation/WriteDiaryNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/navigation/WriteDiaryNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/screen/WriteDiaryScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/screen/WriteDiaryState.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/screen/WriteDiaryViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/utils/extension/getDayOfWeek.kt
  app/src/main/res/img_account_management_kakao/kakao 2.png
  app/src/main/res/img_account_management_kakao/kakao 2@2x.png
  app/src/main/res/img_account_mangement_kakao/kakao 2@3x.png
  app/src/main/res/raw/excepted_rody.json
  app/src/main/res/raw/writing_rody.json
  gradle/libs.versions.toml
Labels: ✨ FEAT, 🌊 문수

#61 [FEAT/#45] 일기쓰기/ 답장확인 버튼 상태 관리
  app/src/main/java/com/sopt/clody/ClodyApp.kt
  app/src/main/java/com/sopt/clody/data/remote/api/AuthService.kt
  app/src/main/java/com/sopt/clody/data/remote/api/DiaryListService.kt
  app/src/main/java/com/sopt/clody/data/remote/api/ReIssueService.kt
  app/src/main/java/com/sopt/clody/data/remote/datasource/AuthDataSource.kt
  app/src/main/java/com/sopt/clody/data/remote/datasource/DiaryListDataSource.kt
  app/src/main/java/com/sopt/clody/data/remote/datasource/ReissueTokenDataSource.kt
  app/src/main/java/com/sopt/clody/data/remote/datasourceimpl/AuthDataSourceImpl.kt
  app/src/main/java/com/sopt/clody/data/remote/datasourceimpl/DiaryListDataSourceImpl.kt
  app/src/main/java/com/sopt/clody/data/remote/datasourceimpl/ReissueTokenDataSourceImpl.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/request/LoginRequestDto.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/request/SignUpRequestDto.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/response/LoginResponseDto.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/response/ReissueTokenResponseDto.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/response/ResponseMonthlyDiaryDto.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/response/SignUpResponseDto.kt
  app/src/main/java/com/sopt/clody/data/repository/AuthRepository.kt
  app/src/main/java/com/sopt/clody/data/repository/DiaryListRepository.kt
  app/src/main/java/com/sopt/clody/data/repository/ReissueTokenRepository.kt
  app/src/main/java/com/sopt/clody/data/repositoryimpl/AuthRepositoryImpl.kt
  app/src/main/java/com/sopt/clody/data/repositoryimpl/DiaryListRepositoryImpl.kt
  app/src/main/java/com/sopt/clody/data/repositoryimpl/ReissueTokenRepositoryImpl.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/signup/SignUpViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/button/ClodyReplyButton.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DailyDiaryCard.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DailyDiaryCardItem.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/MonthlyDiaryList.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/screen/DiaryListState.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/screen/DiaryListViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/calendar/ClodyCalendar.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/component/DiaryStateButton.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: ✨ FEAT, 🌩️ 연진

#62 [FEAT/#58] 닉네임 변경 API 연결
  app/src/main/java/com/sopt/clody/data/remote/api/AccountManagementService.kt
  app/src/main/java/com/sopt/clody/data/remote/datasource/AccountManagementDataSource.kt
  app/src/main/java/com/sopt/clody/data/remote/datasourceimpl/AccountManagementDataSourceImpl.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/RequestModifyNicknameDto.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/ResponseModifyNicknameDto.kt
  app/src/main/java/com/sopt/clody/data/repository/AccountManagementRepository.kt
  app/src/main/java/com/sopt/clody/data/repositoryimpl/AccountManagementRepositoryImpl.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/NicknameChangeModalBottomSheet.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/AccountManagementScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/AccountManagementViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/UserNicknameState.kt
Labels: ✨ FEAT, 🔥 민재

#64 [FEAT/#63] 회원탈퇴 API 연결
  app/src/main/java/com/sopt/clody/data/remote/api/AccountManagementService.kt
  app/src/main/java/com/sopt/clody/data/remote/datasource/AccountManagementDataSource.kt
  app/src/main/java/com/sopt/clody/data/remote/datasourceimpl/AccountManagementDataSourceImpl.kt
  app/src/main/java/com/sopt/clody/data/repository/AccountManagementRepository.kt
  app/src/main/java/com/sopt/clody/data/repositoryimpl/AccountManagementRepositoryImpl.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/AccountManagementScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/AccountManagementViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/RevokeAccountState.kt
Labels: ✨ FEAT, 🔥 민재

#65 [FEAT/#60] 일기 응답 API 연결 및 분기처리
  app/src/main/java/com/sopt/clody/ClodyApp.kt
  app/src/main/java/com/sopt/clody/data/remote/api/DiaryTimeService.kt
  app/src/main/java/com/sopt/clody/data/remote/api/ReplyDiaryService.kt
  app/src/main/java/com/sopt/clody/data/remote/datasource/DiaryTimeDataSource.kt
  app/src/main/java/com/sopt/clody/data/remote/datasource/ReplyDiaryDataSource.kt
  app/src/main/java/com/sopt/clody/data/remote/datasourceimpl/AccountManagementDataSourceImpl.kt
  app/src/main/java/com/sopt/clody/data/remote/datasourceimpl/DiaryTimeDataSourceImpl.kt
  app/src/main/java/com/sopt/clody/data/remote/datasourceimpl/ReplyDiaryDataSourceImpl.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/ResponseReplyDiaryDto.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/ResponseWriteDiaryDto.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/response/ResponseDiaryTimeDto.kt
  app/src/main/java/com/sopt/clody/data/repository/DiaryTimeRepository.kt
  app/src/main/java/com/sopt/clody/data/repository/ReplyDiaryRepository.kt
  app/src/main/java/com/sopt/clody/data/repositoryimpl/AccountManagementRepositoryImpl.kt
  app/src/main/java/com/sopt/clody/data/repositoryimpl/DiaryTimeRepositoryImpl.kt
  app/src/main/java/com/sopt/clody/data/repositoryimpl/ReplyDiaryRepositoryImpl.kt
  app/src/main/java/com/sopt/clody/di/ApiModule.kt
  app/src/main/java/com/sopt/clody/di/DataSourceModule.kt
  app/src/main/java/com/sopt/clody/di/RepositoryModule.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DailyDiaryCard.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/MonthlyDiaryList.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/navigation/DiaryListNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/navigation/DiaryListNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/screen/DiaryListScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/calendar/ClodyCalendar.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/calendar/component/MonthlyItem.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/component/DiaryStateButton.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/navigation/HomeNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/navigation/HomeNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/sopt/clody/presentation/ui/navigatior/MainNavHost.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replydiary/ReplyDiaryScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replydiary/ReplyDiaryState.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replydiary/ReplyDiaryViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replydiary/navigation/ReplyNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/navigation/ReplyLoadingNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/navigation/ReplyLoadingNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/screen/ReplyLoadingScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/screen/ReplyLoadingState.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/screen/ReplyLoadingViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/UserInfoState.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/navigation/WriteDiaryNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/navigation/WriteDiaryNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/screen/WriteDiaryScreen.kt
Labels: ✨ FEAT, 🌊 문수

#74 [FEAT/#69] 임시 자동로그인 구현
  app/src/main/java/com/sopt/clody/presentation/ui/auth/signup/SignUpViewModel.kt
Labels: ✨ FEAT, 🌊 문수

#78 [REFACTOR/#72] 일기쓰기/답장확인 버튼 하단 고정 및 상태관리
  app/src/main/java/com/sopt/clody/domain/model/ButtonStateData.kt
  app/src/main/java/com/sopt/clody/domain/model/DiaryData.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/component/DiaryStateButton.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeViewModel.kt
Labels: ♻️ REFACTOR, 🌩️ 연진

#79 [FEAT/#67] 로그아웃 구현
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/AccountManagementScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/AccountManagementViewModel.kt
Labels: ✨ FEAT, 🔥 민재

#80 [FIX/#73] 피커 오류 해결
  app/src/main/java/com/sopt/clody/presentation/ui/component/timepicker/ClodyPicker.kt
Labels: 🔥 민재, 🛠️ FIX

#82 [FIX/#77] 온보딩 알림설정 페이지 선택값 반영
  app/src/main/java/com/sopt/clody/presentation/ui/auth/component/timepicker/BottomSheetTimePicker.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/screen/TimeReminderScreen.kt
Labels: 🔥 민재, 🛠️ FIX

#81 [REFACTOR/#75] 일기 답변확인 로딩 페이지 뒤로가기 로직 변경
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/navigation/DiaryListNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/navigation/DiaryListNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/navigation/HomeNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/navigation/HomeNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/navigation/ReplyLoadingNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/navigation/ReplyLoadingNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/screen/ReplyLoadingScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/navigation/WriteDiaryNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/navigation/WriteDiaryNavigator.kt
Labels: ♻️ REFACTOR, 🌊 문수

#87 [FIX/#86] 일기 모아보기 페이지 수정
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DailyDiaryCard.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DailyDiaryCardItem.kt
Labels: 🔥 민재, 🛠️ FIX

#84 [REFACTOR#47] Splash 화면 설정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/clody/presentation/ui/main/MainActivity.kt
  app/src/main/res/drawable/ic_splash_logo.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/themes.xml
Labels: ♻️ REFACTOR, 🌩️ 연진

#97 [REFACTOR/#96] 클러버개수 변수명 변경
  app/src/main/java/com/sopt/clody/data/remote/dto/response/MonthlyCalendarResponseDto.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/response/ResponseMonthlyDiaryDto.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeScreen.kt
Labels: ♻️ REFACTOR, 🌩️ 연진

#98 [FIX/#92] QA 피드백 반영
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/screen/ReplyLoadingScreen.kt
  app/src/main/res/drawable-xhdpi/img_reply_logo.png
  app/src/main/res/drawable-xxhdpi/img_reply_logo.png
  app/src/main/res/drawable/img_reply_logo.png
Labels: 🌊 문수, 🛠️ FIX

#100 [Fix/#99] 데모데이 용 답장시간 변경 및 응답확인 에러 대응화면
  app/src/main/java/com/sopt/clody/presentation/ui/replydiary/ReplyDiaryScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replydiary/ReplyDiaryState.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replydiary/ReplyDiaryViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/screen/ReplyLoadingScreen.kt
  app/src/main/res/drawable/ic_not_found.xml
Labels: 🌊 문수, 🛠️ FIX

#102 [HOTFIX/#101] 오타 수정
  app/src/main/java/com/sopt/clody/presentation/ui/replydiary/ReplyDiaryScreen.kt
Labels: 🚨 HOTFIX, 🌊 문수

#104 [HOTFIX/#103] 약관동의화면 Back Handing
  app/src/main/java/com/sopt/clody/presentation/ui/auth/navigation/AuthNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/screen/TermsOfServiceScreen.kt
Labels: 🚨 HOTFIX, 🌊 문수

#108 [FIX/#107] 클로버 컬러 조건 변경
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DailyDiaryCard.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/calendar/component/DayItem.kt
Labels: 🌩️ 연진, 🛠️ FIX

#106 [FIX/#105] Dialog Button Single Click
  app/src/main/java/com/sopt/clody/presentation/ui/component/dialog/ClodyDialog.kt
Labels: 🌊 문수, 🛠️ FIX

#110 [FIX/#109] splash 로고 변경
  app/src/main/res/drawable-xhdpi/img_splash_logo.png
  app/src/main/res/drawable-xxhdpi/img_splash_logo.png
  app/src/main/res/drawable/img_splash_logo.png
Labels: 🌩️ 연진, 🛠️ FIX

#112 [Fix/#111] 타이머 제한 설정 및 일기응답 스크롤 추가
  app/src/main/java/com/sopt/clody/presentation/ui/replydiary/ReplyDiaryScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/screen/ReplyLoadingScreen.kt
Labels: 🌊 문수, 🛠️ FIX

#115 [REFACTOR/#114] 일기 모아보기, 설정 페이지 스트링 추출
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DailyDiaryCard.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DailyDiaryCardItem.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DiaryListTopAppBar.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/NicknameChangeModalBottomSheet.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/SettingBottomSheetTimePicker.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/AccountManagementScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/NotificationSettingScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/SettingScreen.kt
  app/src/main/res/values/strings.xml
Labels: ♻️ REFACTOR, 🔥 민재
