Repository Team-Clody/Clody_Android, pull requests merged in 2024-08, with the labels that each got.

#119 [FIX/#116] 회원가입 중 캘린더 api 호출 삭제
  app/src/main/java/com/sopt/clody/presentation/ui/auth/signup/SignUpViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/navigation/HomeNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/navigatior/MainNavHost.kt
Labels: 🌩️ 연진, 🛠️ FIX

#124 [FEAT/#121] "캘린더뷰 > 리스트뷰" 연,월 값 반영
  app/src/main/java/com/sopt/clody/presentation/ui/auth/navigation/AuthNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/screen/GuideScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/signup/SignUpScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/navigation/DiaryListNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/navigation/DiaryListNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/screen/DiaryListScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/navigation/HomeNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/navigation/HomeNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/navigatior/MainNavHost.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replydiary/ReplyDiaryScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replydiary/navigation/ReplyNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/navigation/ReplyLoadingNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/navigation/ReplyLoadingNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/screen/ReplyLoadingScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/navigation/SettingNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/navigation/WriteDiaryNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/navigation/WriteDiaryNavigator.kt
Labels: ✨ FEAT, 🔥 민재

#122 [REFACTOR/#118] 닉네임 유효성 검사 및 Callback to Coroutine
  app/src/main/java/com/sopt/clody/presentation/ui/auth/component/textfield/NickNameTextField.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/screen/NicknameScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/signup/SignUpScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/signup/SignUpViewModel.kt
  app/src/main/res/values/strings.xml
Labels: ♻️ REFACTOR, 🌊 문수

#128 [REFACTOR/#120] 스플래쉬 화면 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/clody/presentation/ui/auth/signup/SignUpScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/splash/SplashScreen.kt
  app/src/main/res/values/themes.xml
Labels: ♻️ REFACTOR, 🌩️ 연진

#130 [REFACTOR] 설정 페이지 Route, Screen 개선
  app/src/main/java/com/sopt/clody/presentation/ui/component/FailureScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/LoadingScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/screen/DiaryListScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/AccountManagementLogoutOption.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/AccountManagementNicknameOption.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/AccountManagementRevokeOption.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/LogoutDialog.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/NicknameChangeBottomSheet.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/NotificationSettingSwitch.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/NotificationSettingTime.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/NotificationSettingTimePicker.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/SettingAppVersion.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/AccountManagementScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/NotificationSettingScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/SettingScreen.kt
  app/src/main/res/values/strings.xml
Labels: ♻️ REFACTOR, 🔥 민재

#135 [REFACTOR/#127] 일기작성 Toast Message추가 및 상태관리 리팩토링
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/screen/WriteDiaryScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/screen/WriteDiaryViewModel.kt
  app/src/main/res/values/strings.xml
Labels: ♻️ REFACTOR, ➕ ADD, 🌊 문수

#138 [REFACTOR/#136] 일기 로딩 시간 계산 수정
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/screen/ReplyLoadingScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/screen/ReplyLoadingViewModel.kt
  app/src/main/res/raw/writing_rody.json
Labels: ♻️ REFACTOR, 🌊 문수

#140 [REFACTOR/#132] 일기모아보기 페이지 Route, Screen 개선
  app/src/main/java/com/sopt/clody/presentation/ui/component/FailureScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/bottomsheet/DiaryDeleteSheet.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DailyDiaryCard.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DailyDiaryCardContent.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DiaryListTopAppBar.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/MonthlyDiaryList.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/navigation/DiaryListNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/screen/DeleteDiaryListState.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/screen/DiaryDeleteState.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/screen/DiaryListScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/screen/DiaryListState.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/screen/DiaryListViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/res/values/strings.xml
Labels: ♻️ REFACTOR, 🔥 민재

#143 [UI/#142] 에러 대응 화면 및 다이얼로그 공통 컴포넌트 추가
  app/src/main/java/com/sopt/clody/presentation/ui/component/FailureScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/dialog/FailureDialog.kt
  app/src/main/res/drawable-xhdpi/img_failure_screen_clody.png
  app/src/main/res/drawable-xxhdpi/img_failure_screen_clody.png
  app/src/main/res/drawable/ic_failure_dialog.xml
  app/src/main/res/drawable/img_failure_screen_clody.png
  app/src/main/res/values/strings.xml
Labels: 🎨 UI, 🔥 민재

#146 [FEAT/#144] 닉네임 변경 완료 시 토스트 메시지 노출
  app/src/main/java/com/sopt/clody/presentation/ui/component/toast/ClodyToastMessage.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/AccountManagementScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/AccountManagementViewModel.kt
  app/src/main/res/values/strings.xml
Labels: ✨ FEAT, 🔥 민재

#148 [FEAT/#147] 닉네임 변경 시 유효성 검사
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/NicknameChangeBottomSheet.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/NicknameChangeTextField.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/AccountManagementScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/AccountManagementViewModel.kt
Labels: ✨ FEAT, 🔥 민재

#152 [FEAT/#141] 일기 모아보기 페이지 빈 리스트 대응화면 추가
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/EmptyDiaryList.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/screen/DiaryListScreen.kt
  app/src/main/res/values/strings.xml
Labels: ✨ FEAT, 🔥 민재

#145 [FEAT/#137] FCM Token 전송 및 알림 시간 설정
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/clody/ClodyApp.kt
  app/src/main/java/com/sopt/clody/data/ClodyFirebaseMessagingService.kt
  app/src/main/java/com/sopt/clody/data/remote/api/NotificationService.kt
  app/src/main/java/com/sopt/clody/data/remote/datasource/NotificationDataSource.kt
  app/src/main/java/com/sopt/clody/data/remote/datasourceimpl/NotificationDataSourceImpl.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/request/RequestSendNotificationDto.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/request/SignUpRequestDto.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/response/ResponseSendNotificationDto.kt
  app/src/main/java/com/sopt/clody/data/repository/NotificationRepository.kt
  app/src/main/java/com/sopt/clody/data/repositoryimpl/NotificationRepositoryImpl.kt
  app/src/main/java/com/sopt/clody/di/ApiModule.kt
  app/src/main/java/com/sopt/clody/di/DataSourceModule.kt
  app/src/main/java/com/sopt/clody/di/RepositoryModule.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/navigation/AuthNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/signup/SignUpViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/timereminder/TimeReminderScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/timereminder/TimeReminderState.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/timereminder/TimeReminderViewModel.kt
  app/src/main/res/values/strings.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: ✨ FEAT, 🌊 문수

#139 [REFACTOR/#131] 홈 Screen 캘린더 및 일기리스트 state 관리
  app/src/main/java/com/sopt/clody/domain/model/DiaryDateData.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/calendar/ClodyCalendar.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/CalendarState.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/DailyDiariesState.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/AccountManagementViewModel.kt
Labels: ♻️ REFACTOR, 🌩️ 연진

#154 [FEAT/#153] 일기 모아보기 페이지 답장확인 버튼 분기처리
  app/src/main/java/com/sopt/clody/data/remote/dto/response/ResponseMonthlyDiaryDto.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DailyDiaryCard.kt
Labels: ✨ FEAT, 🔥 민재

#150 [FEAT/#149] 설정 화면 앱 버전 받아오기
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/SettingOption.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/SettingVersionInfo.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/SettingScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/SettingViewModel.kt
  app/src/main/res/values/strings.xml
Labels: ✨ FEAT, 🔥 민재

#159 [FIX/#158] 캘린더 및 일기 API 중복 호출 제거
  app/src/main/java/com/sopt/clody/presentation/ui/home/calendar/ClodyCalendar.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/calendar/component/HorizontalDivider.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/ScrollableCalendar.kt
Labels: 🌩️ 연진, 🛠️ FIX

#160 [FEAT/#157] "설정 > 기타 옵션들" 네비게이션 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/clody/presentation/ui/navigatior/MainNavHost.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/navigation/SettingNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/navigation/SettingNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/SettingOptionUrls.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/SettingScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/WebViewScreen.kt
Labels: ✨ FEAT, 🔥 민재

#156 [REFACTOR/#155] 온보딩 알람설정 기본 시간 적용
  app/src/main/java/com/sopt/clody/presentation/ui/auth/timereminder/TimeReminderViewModel.kt
Labels: 🌊 문수, 🛠️ FIX

#164 [Refactor/#83] 클로버 획득 Dialog 분기처리
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DailyDiaryCard.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/MonthlyDiaryList.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/navigation/DiaryListNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/screen/DiaryListScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/navigation/HomeNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replydiary/ReplyDiaryScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/navigation/ReplyLoadingNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/navigation/ReplyLoadingNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/screen/ReplyLoadingScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/navigation/WriteDiaryNavigator.kt
Labels: ♻️ REFACTOR, 🌊 문수

#163 [Fix/#161] 과거일기 로딩시간 계산 수정
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/screen/ReplyLoadingScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/screen/ReplyLoadingState.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/screen/ReplyLoadingViewModel.kt
Labels: 🌊 문수, 🛠️ FIX

#166 [FEAT/#162] 클로버 분기처리 추가
  app/src/main/java/com/sopt/clody/domain/model/DiaryIconType.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/calendar/ClodyCalendar.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/calendar/component/DayItem.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/calendar/component/MonthlyItem.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/component/HomeTopAppBar.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/model/CalendarDateData.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/model/DiaryDateData.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeViewModel.kt
  app/src/main/res/drawable/ic_home_today_written_clover.xml
Labels: ✨ FEAT, 🌩️ 연진

#168 [Feat/#165] 온보딩, 일기작성, 일기로딩, 일기답장 에러대응
  app/src/main/java/com/sopt/clody/di/NetworkModule.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/screen/NicknameScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/signup/SignUpViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/timereminder/TimeReminderScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/timereminder/TimeReminderViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/FailureScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replydiary/ReplyDiaryScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replydiary/ReplyDiaryState.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replydiary/ReplyDiaryViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/screen/ReplyLoadingScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/screen/ReplyLoadingViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/screen/WriteDiaryScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/screen/WriteDiaryViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/utils/network/NetworkErrorMessage.kt
  app/src/main/java/com/sopt/clody/presentation/utils/network/NetworkUtil.kt
Labels: ✨ FEAT, 🌊 문수

#170 [FEAT/#151] "설정 > 알림설정" 페이지 구현
  app/src/main/java/com/sopt/clody/data/remote/api/NotificationService.kt
  app/src/main/java/com/sopt/clody/data/remote/datasource/NotificationDataSource.kt
  app/src/main/java/com/sopt/clody/data/remote/datasourceimpl/NotificationDataSourceImpl.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/response/ResponseNotificationInfoDto.kt
  app/src/main/java/com/sopt/clody/data/repository/NotificationRepository.kt
  app/src/main/java/com/sopt/clody/data/repositoryimpl/NotificationRepositoryImpl.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/accountmanagement/component/AccountManagementLogoutOption.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/accountmanagement/component/AccountManagementNicknameOption.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/accountmanagement/component/AccountManagementRevokeOption.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/accountmanagement/component/LogoutDialog.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/accountmanagement/component/NicknameChangeBottomSheet.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/accountmanagement/component/NicknameChangeTextField.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/accountmanagement/screen/AccountManagementScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/accountmanagement/screen/AccountManagementViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/accountmanagement/screen/RevokeAccountState.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/accountmanagement/screen/UserInfoState.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/accountmanagement/screen/UserNicknameState.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/navigation/SettingNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/notificationsetting/component/DiaryAlarmSwitch.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/notificationsetting/component/NotificationSettingTime.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/notificationsetting/component/NotificationSettingTimePicker.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/notificationsetting/component/ReplyAlarmSwitch.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/notificationsetting/screen/DiaryAlarmChangeState.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/notificationsetting/screen/NotificationInfoState.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/notificationsetting/screen/NotificationSettingScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/notificationsetting/screen/NotificationSettingViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/notificationsetting/screen/NotificationTimeChangeState.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/notificationsetting/screen/ReplyAlarmChangeState.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/NotificationSettingScreen.kt
  app/src/main/res/values/strings.xml
Labels: ✨ FEAT, 🔥 민재

#173 [UI/#172] 리플 효과 개선
  app/src/main/java/com/sopt/clody/presentation/ui/auth/component/textfield/NickNameTextField.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/timereminder/TimeReminderScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/bottomsheet/DiaryDeleteSheet.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DailyDiaryCard.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DiaryListTopAppBar.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/calendar/component/DailyDiaryListItem.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/calendar/component/DayItem.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/component/YearAndMonthTitle.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/AccountManagementLogoutOption.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/AccountManagementNicknameOption.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/AccountManagementRevokeOption.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/NicknameChangeTextField.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/component/bottomsheet/DeleteWriteDiaryBottomSheet.kt
Labels: 🎨 UI, 🔥 민재

#176 [FEAT/#167 ] 버튼 상태 관리 추가 및 수정
  app/src/main/java/com/sopt/clody/data/remote/dto/response/MonthlyCalendarResponseDto.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/button/ClodyReplyButton.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/calendar/ClodyCalendar.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/calendar/component/DailyDiaryListItem.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/component/DiaryStateButton.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/component/HomeTopAppBar.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/ScrollableCalendar.kt
Labels: ✨ FEAT, 🌩️ 연진

#181 [FEAT/#177] 홈 에러 대응
  app/src/main/java/com/sopt/clody/presentation/ui/home/component/DiaryStateButton.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeViewModel.kt
Labels: ✨ FEAT, 🌩️ 연진

#178 [FEAT/#174] 일기 모아보기 에러대응
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/screen/DiaryListScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/screen/DiaryListViewModel.kt
Labels: ✨ FEAT, 🔥 민재

#180 [Fix/#169] 2차 스프린트 QA 반영
  app/src/main/java/com/sopt/clody/data/remote/interceptor/AuthInterceptor.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/component/button/NextButton.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/screen/GuideScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/screen/NicknameScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/screen/TermsOfServiceScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/timereminder/TimeReminderScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replydiary/CloverDialog.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replydiary/ReplyDiaryScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replydiary/navigation/ReplyNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/navigation/ReplyLoadingNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/screen/ReplyLoadingScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/AccountManagementScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/AccountManagementViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/LogOutState.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/component/textfield/WriteDiaryTextField.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/component/tooltip/TooltipIcon.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/navigation/WriteDiaryNavigator.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/screen/WriteDiaryScreen.kt
  app/src/main/res/drawable/ic_terms_check_on_23.xml
  app/src/main/res/drawable/ic_terms_check_on_25.xml
  app/src/main/res/drawable/ic_writediary_add.xml
  app/src/main/res/raw/writing_rody.json
  app/src/main/res/values/strings.xml
Labels: 🌊 문수, 🛠️ FIX

#191 [FEAT/#187] 로그인 FCM 토큰 추가
  app/src/main/java/com/sopt/clody/data/remote/dto/request/LoginRequestDto.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/signup/SignUpViewModel.kt
Labels: ✨ FEAT, 🌊 문수

#190 [Feat/#189] 일기작성 분기처리
  app/src/main/java/com/sopt/clody/data/remote/dto/ResponseWriteDiaryDto.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/response/ResponseDiaryTimeDto.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/screen/ReplyLoadingViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/screen/WriteDiaryScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/screen/WriteDiaryState.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/screen/WriteDiaryViewModel.kt
Labels: ✨ FEAT, 🌊 문수

#186 [FEAT/#179] "설정 > 프로필 및 계정관리" 에러대응
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/screen/DiaryListScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/AccountManagementScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/AccountManagementViewModel.kt
Labels: ✨ FEAT, 🔥 민재
