Repository Team-Clody/Clody_Android, pull requests merged in 2025-07, with the labels that each got.

#295 [BUGFIX/#294] 발견한 오류들을 개선합니다.
  app/src/main/java/com/sopt/clody/di/AppUpdateModule.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/timereminder/TimeReminderScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/calendar/component/DailyDiaryListItem.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/screen/WriteDiaryScreen.kt
Labels: 🌊 문수, 🛠️ FIX

#301 [FEAT/#300] 시스템 점검을 구현합니다.
  app/build.gradle.kts
  app/src/main/java/com/sopt/clody/data/remote/appupdate/AppUpdateCheckerImpl.kt
  app/src/main/java/com/sopt/clody/data/remote/datasource/RemoteConfigDataSource.kt
  app/src/main/java/com/sopt/clody/di/AppUpdateModule.kt
  app/src/main/java/com/sopt/clody/domain/appupdate/AppUpdateChecker.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/dialog/InspectionDialog.kt
  app/src/main/java/com/sopt/clody/presentation/ui/splash/SplashContract.kt
  app/src/main/java/com/sopt/clody/presentation/ui/splash/SplashScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/splash/SplashViewModel.kt
  app/src/main/res/drawable/img_inspection_dialog.png
Labels: ✨ FEAT, 🔥 민재, 🌊 문수

#302 [Feat/#299] 영어 버전 기능 분기 처리를 진행합니다.
  app/src/main/java/com/sopt/clody/presentation/di/LanguageModule.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/component/textfield/NickNameTextField.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/signup/SignUpContract.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/signup/SignUpScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/signup/SignUpViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/signup/page/NicknamePage.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/signup/page/TermsOfServicePage.kt
  app/src/main/java/com/sopt/clody/presentation/ui/login/LoginContract.kt
  app/src/main/java/com/sopt/clody/presentation/ui/login/LoginScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/login/LoginType.kt
  app/src/main/java/com/sopt/clody/presentation/ui/login/LoginViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/NicknameChangeBottomSheet.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/component/NicknameChangeTextField.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/AccountManagementScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/AccountManagementViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/SettingOptionUrls.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/SettingScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/SettingViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/splash/SplashScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/component/textfield/WriteDiaryTextField.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/component/topbar/WriteDiaryTopBar.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/screen/WriteDiaryScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/screen/WriteDiaryViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/utils/language/LanguageProvider.kt
  app/src/main/java/com/sopt/clody/presentation/utils/language/LanguageProviderImpl.kt
  app/src/main/java/com/sopt/clody/ui/theme/Theme.kt
  app/src/main/java/com/sopt/clody/ui/theme/Type.kt
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values/strings.xml
Labels: ✨ FEAT, 🔥 민재
