Repository Team-Clody/Clody_Android, pull requests merged in 2025-06, with the labels that each got.

#267 [Feat/#266] 이어쓰기 알림설정을 추가한 UI를 구현합니다.
  app/src/main/java/com/sopt/clody/data/remote/dto/request/SendNotificationRequestDto.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/response/NotificationInfoResponseDto.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/response/SendNotificationResponseDto.kt
  app/src/main/java/com/sopt/clody/domain/Notification.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/timereminder/TimeReminderViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/notificationsetting/component/NotificationSettingTimePicker.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/notificationsetting/component/NotificationSwitch.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/notificationsetting/component/NotificationTimeSelector.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/notificationsetting/component/ReplyAlarmSwitch.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/notificationsetting/screen/DiaryAlarmChangeState.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/notificationsetting/screen/NotificationChangeState.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/notificationsetting/screen/NotificationSettingScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/notificationsetting/screen/NotificationSettingViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/notificationsetting/screen/ReplyAlarmChangeState.kt
  app/src/main/java/com/sopt/clody/presentation/utils/extension/StringExt.kt
  app/src/main/res/values/strings.xml
Labels: ✨ FEAT, 🔥 민재

#271 [Feat/#265] 임시저장 API연결을 진행합니다.
  app/build.gradle.kts
  app/src/main/java/com/sopt/clody/data/remote/api/DiaryService.kt
  app/src/main/java/com/sopt/clody/data/remote/datasource/DiaryRemoteDataSource.kt
  app/src/main/java/com/sopt/clody/data/remote/datasourceimpl/DiaryRemoteDataSourceImpl.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/request/SaveDraftDiaryRequestDto.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/response/DraftDiariesResponseDto.kt
  app/src/main/java/com/sopt/clody/data/repositoryimpl/DiaryRepositoryImpl.kt
  app/src/main/java/com/sopt/clody/domain/model/DraftDiaryContents.kt
  app/src/main/java/com/sopt/clody/domain/repository/DiaryRepository.kt
  app/src/main/java/com/sopt/clody/domain/usecase/FetchDraftDiaryUseCase.kt
  app/src/main/java/com/sopt/clody/domain/usecase/SaveDraftDiaryUseCase.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/dialog/ClodyDialog.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/component/textfield/WriteDiaryTextField.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/screen/WriteDiaryScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/screen/WriteDiaryViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/utils/extension/LifeCycle.kt
  app/src/main/java/com/sopt/clody/presentation/utils/network/ErrorMessages.kt
  app/src/test/java/com/sopt/clody/FakeDiaryRepository.kt
  app/src/test/java/com/sopt/clody/WriteDiaryViewModelTest.kt
  app/src/test/java/com/sopt/clody/datasource/FakeDiaryRemoteDataSource.kt
  app/src/test/java/com/sopt/clody/repositoryimpl/DiaryRepositoryImplTest.kt
  gradle/libs.versions.toml
Labels: ✨ FEAT, 🌊 문수

#277 [REFACTOR/#276] 일기작성 뒤로가기 수정 및 삭제 바텀시트 UI 수정을 진행합니다.
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/component/bottomsheet/DeleteWriteDiaryBottomSheet.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/screen/WriteDiaryScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/screen/WriteDiaryViewModel.kt
Labels: ♻️ REFACTOR, 🌊 문수

#275 [FEAT/#270] 임시저장 상태에 따른 분기를 추가합니다.
  app/src/main/java/com/sopt/clody/data/remote/dto/response/DailyDiariesResponseDto.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/response/MonthlyCalendarResponseDto.kt
  app/src/main/java/com/sopt/clody/domain/model/ReplyStatus.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/calendar/ClodyCalendar.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/calendar/component/DailyDiaryListItem.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/calendar/component/DayItem.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/component/DiaryStateButton.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/ScrollableCalendar.kt
  app/src/main/java/com/sopt/clody/presentation/ui/type/DiaryCloverType.kt
  app/src/main/res/drawable/ic_home_draft_saved_clover.xml
  app/src/main/res/drawable/ic_home_expired_written_clover.xml
Labels: ✨ FEAT, 🌊 문수

#279 [Chore/#278] 이어쓰기 알림설정 완료 토스트 위치를 수정합니다.
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeScreen.kt
Labels: ❤️‍🩹 CHORE, 🔥 민재

#288 [MOD/#287] 앱 버전 업데이트
  app/build.gradle.kts
Labels: ❤️‍🩹 CHORE, 🌊 문수

#284 [REFACTOR/#283] 하드코딩된 문자열 리소스를 추출하여 i18n 적용 준비 합니다.
  app/src/main/java/com/sopt/clody/presentation/ui/auth/component/button/NextButton.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/component/timepicker/BottomSheetTimePicker.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/signup/page/NicknamePage.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/timereminder/TimeReminderScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/timereminder/TimeReminderViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/bottomsheet/DiaryDeleteSheet.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/timepicker/YearMonthPicker.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/calendar/component/DailyDiaryListItem.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/calendar/component/WeekHeader.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/component/CloverCount.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/component/DiaryStateButton.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/component/YearAndMonthTitle.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/component/QuickReplyAdButton.kt
  app/src/main/java/com/sopt/clody/presentation/ui/splash/SplashScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/component/bottomsheet/DeleteWriteDiaryBottomSheet.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/component/button/AddDiaryEntryFAB.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/component/button/SendButton.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/component/textfield/WriteDiaryTextField.kt
  app/src/main/java/com/sopt/clody/presentation/utils/extension/TimePeriod.kt
  app/src/main/java/com/sopt/clody/presentation/utils/extension/YearMonthLabelUtil.kt
  app/src/main/res/values/strings.xml
Labels: ♻️ REFACTOR, 🌊 문수

#286 [FEAT/#285] 보안 취약점 대응 및 강화를 합니다.
  app/build.gradle.kts
  app/src/main/java/com/sopt/clody/core/login/KakaoLoginSdk.kt
  app/src/main/java/com/sopt/clody/core/security/login/DefaultLoginSecurityChecker.kt
  app/src/main/java/com/sopt/clody/core/security/login/LoginSecurityChecker.kt
  app/src/main/java/com/sopt/clody/core/security/login/SecurityModule.kt
  app/src/main/java/com/sopt/clody/core/security/weview/SecureWebViewClient.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/signup/SignUpContract.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/signup/SignUpScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/signup/SignUpViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/signup/navigation/SignUpNavigation.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/signup/page/TermsOfServicePage.kt
  app/src/main/java/com/sopt/clody/presentation/ui/main/ClodyNavHost.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/navigation/SettingNavigation.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/SettingScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/webview/WebViewNavGraph.kt
  app/src/main/java/com/sopt/clody/presentation/ui/webview/WebViewScreen.kt
  app/src/main/java/com/sopt/clody/presentation/utils/appupdate/AppUpdateUtils.kt
  app/src/main/res/values/strings.xml
Labels: ✨ FEAT, 🌊 문수
