Repository Team-Clody/Clody_Android, pull requests merged in 2025-03, with the labels that each got.

#229 [Feat/#223] 담당 뷰에 대한 Amplitude를 연결합니다.
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/clody/ClodyApp.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/timereminder/TimeReminderScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/component/DailyDiaryCard.kt
  app/src/main/java/com/sopt/clody/presentation/ui/diarylist/screen/DiaryListScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/calendar/component/MonthlyItem.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replydiary/ReplyDiaryScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/screen/ReplyLoadingScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/AccountManagementScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/SettingScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/screen/WriteDiaryScreen.kt
  app/src/main/java/com/sopt/clody/presentation/utils/amplitude/AmplitudeConstraints.kt
  app/src/main/java/com/sopt/clody/presentation/utils/amplitude/AmplitudeUtils.kt
  gradle/libs.versions.toml
Labels: ✨ FEAT, 🔥 민재

#227 [REFACTOR/#225] 버전 카탈로그 수정 및 Gradle 재설정을 수행합니다.
  app/build.gradle.kts
  app/src/main/java/com/sopt/clody/presentation/ui/auth/component/button/NextButton.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/component/checkbox/CustomCheckBox.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/bottomsheet/ClodyBottomSheet.kt
  build.gradle.kts
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
Labels: ♻️ REFACTOR, 🌊 문수

#232 [FEAT/#231] 전날 일기 작성 기능을 구현합니다.
  app/build.gradle.kts
  app/src/main/java/com/sopt/clody/data/remote/dto/response/DiaryTimeResponseDto.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/bottomsheet/DiaryDeleteSheet.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/component/DiaryStateButton.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/screen/ReplyLoadingViewModel.kt
  app/src/main/res/values/strings.xml
Labels: ✨ FEAT, 🔥 민재

#233 [FEAT/#224] 일기 빠른 답장을 위한 보상형 광고를 구현합니다.
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/clody/core/RewardAdShower.kt
  app/src/main/java/com/sopt/clody/data/ad/RewardAdShowerImpl.kt
  app/src/main/java/com/sopt/clody/data/remote/api/AdService.kt
  app/src/main/java/com/sopt/clody/data/remote/datasource/AdRemoteDataSource.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/base/NullableApiResponse.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/request/AdRequestDto.kt
  app/src/main/java/com/sopt/clody/data/remote/dto/response/DiaryTimeResponseDto.kt
  app/src/main/java/com/sopt/clody/data/repositoryimpl/AdRepositoryImpl.kt
  app/src/main/java/com/sopt/clody/di/AdModule.kt
  app/src/main/java/com/sopt/clody/di/ApiModule.kt
  app/src/main/java/com/sopt/clody/di/RepositoryModule.kt
  app/src/main/java/com/sopt/clody/domain/repository/AdRepository.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/LoadingScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/component/LottieAnimation.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/component/QuickReplyAdButton.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/screen/ReplyLoadingScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/screen/ReplyLoadingViewModel.kt
  app/src/main/res/drawable/ic_replyloading_player.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: ✨ FEAT, 🌊 문수

#235 [REFACTOR] 3차 스프린트 QA를 반영합니다.
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/screen/ReplyLoadingScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/screen/ReplyLoadingViewModel.kt
Labels: ♻️ REFACTOR, 🌊 문수

#237 [REFACTOR/#236] 자체 QA를 진행합니다.
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/clody/presentation/ui/auth/screen/GuideScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/screen/NicknameScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/screen/TermsOfServiceScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/signup/SignUpScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/signup/SignUpViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/auth/timereminder/TimeReminderScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/component/FailureScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/sopt/clody/presentation/ui/navigatior/MainNavHost.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replydiary/ReplyDiaryScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/replyloading/screen/ReplyLoadingScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/splash/SplashScreen.kt
  app/src/main/java/com/sopt/clody/presentation/ui/splash/SplashViewModel.kt
  app/src/main/java/com/sopt/clody/presentation/ui/writediary/screen/WriteDiaryScreen.kt
  app/src/main/java/com/sopt/clody/ui/theme/Theme.kt
  app/src/main/res/values/themes.xml
Labels: ♻️ REFACTOR, 🌊 문수

#242 [FEAT/#226] Git Action CI/CD 워크플로우를 추가합니다.
  .github/workflows/android_cd.yml
  .github/workflows/android_ci.yml
  app/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
Labels: ✨ FEAT, 🌊 문수

#244 [CHORE/#243] 변경된 링크를 반영합니다.
  app/src/main/java/com/sopt/clody/presentation/ui/setting/screen/SettingOptionUrls.kt
Labels: ❤️‍🩹 CHORE, 🔥 민재
